import requests
import streamlit as st

url = "https://ai-content-detector1.p.rapidapi.com/"
headers = {
	"X-RapidAPI-Key": "48d2f885famshdfd0fc1d12c9ddfp17ed19jsn6bf07bb1170c",
	"X-RapidAPI-Host": "ai-content-detector1.p.rapidapi.com"
}

#layout of the page
st.set_page_config(page_title="AI Content Detector", page_icon=":memo:", layout="wide")
#title
st.title("AI Content Detector")

text = st.text_area("Enter text to analyze", "")

if st.button('Analyze Text'):

    params = {
        'text': text ,
        'language': 'en',
        'threshold': 0.5
    }
    # make a request to the API
    response = requests.get(url, headers=headers, params=params)

    data = response.json()
        # display the API response in Streamlity'])
    fkprob = data['fake_probability']
    st.markdown(f'<h5> Computer-written text- Probability:{fkprob}</h5>', unsafe_allow_html=True)
    reporb =data['real_probability']
    st.markdown(f'<h5> Human-written text- Probability:{reporb}</h5>', unsafe_allow_html=True)

    st.markdown(f'<h8> Please note that the probabilities generated by this are estimates based on the input text and may not always be accurate. We do not hold responsibility for any incorrect or misleading results provided . THANK YOU </h8>', unsafe_allow_html=True)


